spring:
  application:
    name: LoF-Dashboard-v2
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lof-dashboard-dev
    username: dev
    password: password