CREATE TABLE IF NOT EXISTS team (
    id SERIAL PRIMARY KEY NOT NULL,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS player (
    id SERIAL PRIMARY KEY NOT NULL,
    summoner_name TEXT NOT NULL
)